name: Bicep IaC lint and validate

# pipeline runs on PR request to main branch, or if manually dispatched
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  workDir: bicep

jobs:
  bicep_lint_and_validate:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - uses: actions/checkout@main

      # Log into Azure
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # This builds the bicep, to check that it has valid syntax
      - name: Bicep Lint
        run: |
          az bicep build --file main.bicep
          cat main.json
        working-directory: ${{ env.workDir }}

      # Bicep Validate
      - name: Bicep Validate
        run: |
          az deployment group validate \
            --resource-group ${{ secrets.AZURE_RG }} \
            --template-file main.bicep \
            --parameters vmssName=demo-vmss adminPassword=${{ secrets.ADMIN_PASSWORD }}
        working-directory: ${{ env.workDir }}
        # For the 'az deployment group validate' command, it deploys to a resource group
        # Change to 'az deployment sub validate' if you want to deploy to the subscription level
